/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * VersionedContentPOC.Server
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export interface Content {
  contentType: string;
  versionId: string;
  contentId: string;
  contentRoot?: ContentRoot;
  language: Language;
  languageBranch?: LanguageBranch;
  versionCreated?: string;
}

/**
 * @nullable
 */
export type ContentPropertyValueDtoValue = unknown | null;

export interface ContentPropertyValueDto {
  inputType?: InputType;
  isRequired?: boolean;
  /** @nullable */
  value?: ContentPropertyValueDtoValue;
}

export interface ContentRoot {
  contentId?: string;
  created?: string;
  /** @nullable */
  startPublish?: string | null;
  /** @nullable */
  stopPublish?: string | null;
}

export type CreateContentRequestPropertiesSchema = {[key: string]: ContentPropertyValueDto};

export interface CreateContentRequest {
  metadata: CreateContentRequestMetadata;
  propertiesSchema: CreateContentRequestPropertiesSchema;
}

export interface CreateContentRequestMetadata {
  /** @nullable */
  contentTypeName: string | null;
  language: Language;
}

export type EventContentAllOf = {
  /** @minLength 1 */
  heading: string;
  startDate: string;
  endDate: string;
};

export type EventContentContentType = typeof EventContentContentType[keyof typeof EventContentContentType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventContentContentType = {
  EventContent: 'EventContent',
} as const;

export type EventContent = Omit<Content & EventContentAllOf, 'contentType'> & {
  contentType: EventContentContentType;
};

export type InputType = typeof InputType[keyof typeof InputType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InputType = {
  None: 'None',
  Input: 'Input',
  TextArea: 'TextArea',
  DatePicker: 'DatePicker',
  DateTimePicker: 'DateTimePicker',
  Select: 'Select',
} as const;

export type Language = typeof Language[keyof typeof Language];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Language = {
  SV: 'SV',
  EN: 'EN',
} as const;

export interface LanguageBranch {
  contentId?: string;
  language?: Language;
  /** @nullable */
  activeVersionId?: string | null;
}

export type NewsContentAllOf = {
  /** @nullable */
  heading: string | null;
  /** @nullable */
  lead?: string | null;
  /** @nullable */
  text: string | null;
};

export type NewsContentContentType = typeof NewsContentContentType[keyof typeof NewsContentContentType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NewsContentContentType = {
  NewsContent: 'NewsContent',
} as const;

export type NewsContent = Omit<Content & NewsContentAllOf, 'contentType'> & {
  contentType: NewsContentContentType;
};

export type UpdateContentRequestPropertiesSchema = {[key: string]: ContentPropertyValueDto};

export interface UpdateContentRequest {
  metadata: UpdateContentRequestMetadata;
  propertiesSchema: UpdateContentRequestPropertiesSchema;
}

export interface UpdateContentRequestMetadata {
  contentId: string;
  /** @nullable */
  currentVersionId: string | null;
  language: Language;
  created: string;
  /** @nullable */
  startPublish: string | null;
  /** @nullable */
  stopPublish: string | null;
  /** @nullable */
  languageTranslations: Language[] | null;
  forceUpdate?: boolean;
}

export type GetApiContentAllParams = {
language?: Language;
};

export type GetApiContentAll200Item = EventContent | NewsContent;

export type GetApiContentCreationschemaParams = {
contentTypeName?: string;
language?: Language;
};

export type PostApiContentCreate200 = EventContent | NewsContent;

export type GetApiContentUpdateschemaParams = {
contentId?: string;
language?: Language;
};

export type PutApiContentUpdate200 = EventContent | NewsContent;

export type GetApiContentVersionsParams = {
contentId?: string;
language?: Language;
};

export type GetApiContentVersions200Item = EventContent | NewsContent;

export type PutApiContentSetasactiveParams = {
versionId?: string;
};

export type PutApiContentPublishParams = {
contentId?: string;
};

export type PutApiContentUnpublishParams = {
contentId?: string;
};

export type DeleteApiContentDeleteParams = {
contentId?: string;
};

export const getApiContentAll = (
    params?: GetApiContentAllParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetApiContentAll200Item[]>> => {
    
    
    return axios.default.get(
      `/api/content/all`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getGetApiContentAllQueryKey = (params?: GetApiContentAllParams,) => {
    return [
    `/api/content/all`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiContentAllQueryOptions = <TData = Awaited<ReturnType<typeof getApiContentAll>>, TError = AxiosError<unknown>>(params?: GetApiContentAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentAll>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiContentAllQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiContentAll>>> = ({ signal }) => getApiContentAll(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiContentAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiContentAllQueryResult = NonNullable<Awaited<ReturnType<typeof getApiContentAll>>>
export type GetApiContentAllQueryError = AxiosError<unknown>


export function useGetApiContentAll<TData = Awaited<ReturnType<typeof getApiContentAll>>, TError = AxiosError<unknown>>(
 params: undefined |  GetApiContentAllParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiContentAll>>,
          TError,
          Awaited<ReturnType<typeof getApiContentAll>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiContentAll<TData = Awaited<ReturnType<typeof getApiContentAll>>, TError = AxiosError<unknown>>(
 params?: GetApiContentAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiContentAll>>,
          TError,
          Awaited<ReturnType<typeof getApiContentAll>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiContentAll<TData = Awaited<ReturnType<typeof getApiContentAll>>, TError = AxiosError<unknown>>(
 params?: GetApiContentAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentAll>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiContentAll<TData = Awaited<ReturnType<typeof getApiContentAll>>, TError = AxiosError<unknown>>(
 params?: GetApiContentAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentAll>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiContentAllQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const getApiContentLatest = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.get(
      `/api/content/latest`,options
    );
  }




export const getGetApiContentLatestQueryKey = () => {
    return [
    `/api/content/latest`
    ] as const;
    }

    
export const getGetApiContentLatestQueryOptions = <TData = Awaited<ReturnType<typeof getApiContentLatest>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentLatest>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiContentLatestQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiContentLatest>>> = ({ signal }) => getApiContentLatest({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiContentLatest>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiContentLatestQueryResult = NonNullable<Awaited<ReturnType<typeof getApiContentLatest>>>
export type GetApiContentLatestQueryError = AxiosError<unknown>


export function useGetApiContentLatest<TData = Awaited<ReturnType<typeof getApiContentLatest>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentLatest>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiContentLatest>>,
          TError,
          Awaited<ReturnType<typeof getApiContentLatest>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiContentLatest<TData = Awaited<ReturnType<typeof getApiContentLatest>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentLatest>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiContentLatest>>,
          TError,
          Awaited<ReturnType<typeof getApiContentLatest>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiContentLatest<TData = Awaited<ReturnType<typeof getApiContentLatest>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentLatest>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiContentLatest<TData = Awaited<ReturnType<typeof getApiContentLatest>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentLatest>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiContentLatestQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const getApiContentTypes = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<string[]>> => {
    
    
    return axios.default.get(
      `/api/content/types`,options
    );
  }




export const getGetApiContentTypesQueryKey = () => {
    return [
    `/api/content/types`
    ] as const;
    }

    
export const getGetApiContentTypesQueryOptions = <TData = Awaited<ReturnType<typeof getApiContentTypes>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentTypes>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiContentTypesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiContentTypes>>> = ({ signal }) => getApiContentTypes({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiContentTypes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiContentTypesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiContentTypes>>>
export type GetApiContentTypesQueryError = AxiosError<unknown>


export function useGetApiContentTypes<TData = Awaited<ReturnType<typeof getApiContentTypes>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentTypes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiContentTypes>>,
          TError,
          Awaited<ReturnType<typeof getApiContentTypes>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiContentTypes<TData = Awaited<ReturnType<typeof getApiContentTypes>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentTypes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiContentTypes>>,
          TError,
          Awaited<ReturnType<typeof getApiContentTypes>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiContentTypes<TData = Awaited<ReturnType<typeof getApiContentTypes>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentTypes>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiContentTypes<TData = Awaited<ReturnType<typeof getApiContentTypes>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentTypes>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiContentTypesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const getApiContentCreationschema = (
    params?: GetApiContentCreationschemaParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CreateContentRequest>> => {
    
    
    return axios.default.get(
      `/api/content/creationschema`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getGetApiContentCreationschemaQueryKey = (params?: GetApiContentCreationschemaParams,) => {
    return [
    `/api/content/creationschema`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiContentCreationschemaQueryOptions = <TData = Awaited<ReturnType<typeof getApiContentCreationschema>>, TError = AxiosError<unknown>>(params?: GetApiContentCreationschemaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentCreationschema>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiContentCreationschemaQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiContentCreationschema>>> = ({ signal }) => getApiContentCreationschema(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiContentCreationschema>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiContentCreationschemaQueryResult = NonNullable<Awaited<ReturnType<typeof getApiContentCreationschema>>>
export type GetApiContentCreationschemaQueryError = AxiosError<unknown>


export function useGetApiContentCreationschema<TData = Awaited<ReturnType<typeof getApiContentCreationschema>>, TError = AxiosError<unknown>>(
 params: undefined |  GetApiContentCreationschemaParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentCreationschema>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiContentCreationschema>>,
          TError,
          Awaited<ReturnType<typeof getApiContentCreationschema>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiContentCreationschema<TData = Awaited<ReturnType<typeof getApiContentCreationschema>>, TError = AxiosError<unknown>>(
 params?: GetApiContentCreationschemaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentCreationschema>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiContentCreationschema>>,
          TError,
          Awaited<ReturnType<typeof getApiContentCreationschema>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiContentCreationschema<TData = Awaited<ReturnType<typeof getApiContentCreationschema>>, TError = AxiosError<unknown>>(
 params?: GetApiContentCreationschemaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentCreationschema>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiContentCreationschema<TData = Awaited<ReturnType<typeof getApiContentCreationschema>>, TError = AxiosError<unknown>>(
 params?: GetApiContentCreationschemaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentCreationschema>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiContentCreationschemaQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const postApiContentCreate = (
    createContentRequest: CreateContentRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PostApiContentCreate200>> => {
    
    
    return axios.default.post(
      `/api/content/create`,
      createContentRequest,options
    );
  }



export const getPostApiContentCreateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiContentCreate>>, TError,{data: CreateContentRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiContentCreate>>, TError,{data: CreateContentRequest}, TContext> => {

const mutationKey = ['postApiContentCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiContentCreate>>, {data: CreateContentRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiContentCreate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiContentCreateMutationResult = NonNullable<Awaited<ReturnType<typeof postApiContentCreate>>>
    export type PostApiContentCreateMutationBody = CreateContentRequest
    export type PostApiContentCreateMutationError = AxiosError<unknown>

    export const usePostApiContentCreate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiContentCreate>>, TError,{data: CreateContentRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiContentCreate>>,
        TError,
        {data: CreateContentRequest},
        TContext
      > => {

      const mutationOptions = getPostApiContentCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const getApiContentUpdateschema = (
    params?: GetApiContentUpdateschemaParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UpdateContentRequest>> => {
    
    
    return axios.default.get(
      `/api/content/updateschema`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getGetApiContentUpdateschemaQueryKey = (params?: GetApiContentUpdateschemaParams,) => {
    return [
    `/api/content/updateschema`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiContentUpdateschemaQueryOptions = <TData = Awaited<ReturnType<typeof getApiContentUpdateschema>>, TError = AxiosError<unknown>>(params?: GetApiContentUpdateschemaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentUpdateschema>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiContentUpdateschemaQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiContentUpdateschema>>> = ({ signal }) => getApiContentUpdateschema(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiContentUpdateschema>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiContentUpdateschemaQueryResult = NonNullable<Awaited<ReturnType<typeof getApiContentUpdateschema>>>
export type GetApiContentUpdateschemaQueryError = AxiosError<unknown>


export function useGetApiContentUpdateschema<TData = Awaited<ReturnType<typeof getApiContentUpdateschema>>, TError = AxiosError<unknown>>(
 params: undefined |  GetApiContentUpdateschemaParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentUpdateschema>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiContentUpdateschema>>,
          TError,
          Awaited<ReturnType<typeof getApiContentUpdateschema>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiContentUpdateschema<TData = Awaited<ReturnType<typeof getApiContentUpdateschema>>, TError = AxiosError<unknown>>(
 params?: GetApiContentUpdateschemaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentUpdateschema>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiContentUpdateschema>>,
          TError,
          Awaited<ReturnType<typeof getApiContentUpdateschema>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiContentUpdateschema<TData = Awaited<ReturnType<typeof getApiContentUpdateschema>>, TError = AxiosError<unknown>>(
 params?: GetApiContentUpdateschemaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentUpdateschema>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiContentUpdateschema<TData = Awaited<ReturnType<typeof getApiContentUpdateschema>>, TError = AxiosError<unknown>>(
 params?: GetApiContentUpdateschemaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentUpdateschema>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiContentUpdateschemaQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const putApiContentUpdate = (
    updateContentRequest: UpdateContentRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PutApiContentUpdate200>> => {
    
    
    return axios.default.put(
      `/api/content/update`,
      updateContentRequest,options
    );
  }



export const getPutApiContentUpdateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiContentUpdate>>, TError,{data: UpdateContentRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof putApiContentUpdate>>, TError,{data: UpdateContentRequest}, TContext> => {

const mutationKey = ['putApiContentUpdate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiContentUpdate>>, {data: UpdateContentRequest}> = (props) => {
          const {data} = props ?? {};

          return  putApiContentUpdate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiContentUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof putApiContentUpdate>>>
    export type PutApiContentUpdateMutationBody = UpdateContentRequest
    export type PutApiContentUpdateMutationError = AxiosError<unknown>

    export const usePutApiContentUpdate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiContentUpdate>>, TError,{data: UpdateContentRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiContentUpdate>>,
        TError,
        {data: UpdateContentRequest},
        TContext
      > => {

      const mutationOptions = getPutApiContentUpdateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const getApiContentVersions = (
    params?: GetApiContentVersionsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetApiContentVersions200Item[]>> => {
    
    
    return axios.default.get(
      `/api/content/versions`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getGetApiContentVersionsQueryKey = (params?: GetApiContentVersionsParams,) => {
    return [
    `/api/content/versions`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiContentVersionsQueryOptions = <TData = Awaited<ReturnType<typeof getApiContentVersions>>, TError = AxiosError<unknown>>(params?: GetApiContentVersionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentVersions>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiContentVersionsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiContentVersions>>> = ({ signal }) => getApiContentVersions(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiContentVersions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiContentVersionsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiContentVersions>>>
export type GetApiContentVersionsQueryError = AxiosError<unknown>


export function useGetApiContentVersions<TData = Awaited<ReturnType<typeof getApiContentVersions>>, TError = AxiosError<unknown>>(
 params: undefined |  GetApiContentVersionsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentVersions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiContentVersions>>,
          TError,
          Awaited<ReturnType<typeof getApiContentVersions>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiContentVersions<TData = Awaited<ReturnType<typeof getApiContentVersions>>, TError = AxiosError<unknown>>(
 params?: GetApiContentVersionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentVersions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiContentVersions>>,
          TError,
          Awaited<ReturnType<typeof getApiContentVersions>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiContentVersions<TData = Awaited<ReturnType<typeof getApiContentVersions>>, TError = AxiosError<unknown>>(
 params?: GetApiContentVersionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentVersions>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiContentVersions<TData = Awaited<ReturnType<typeof getApiContentVersions>>, TError = AxiosError<unknown>>(
 params?: GetApiContentVersionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentVersions>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiContentVersionsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const putApiContentSetasactive = (
    params?: PutApiContentSetasactiveParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.put(
      `/api/content/setasactive`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getPutApiContentSetasactiveMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiContentSetasactive>>, TError,{params?: PutApiContentSetasactiveParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof putApiContentSetasactive>>, TError,{params?: PutApiContentSetasactiveParams}, TContext> => {

const mutationKey = ['putApiContentSetasactive'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiContentSetasactive>>, {params?: PutApiContentSetasactiveParams}> = (props) => {
          const {params} = props ?? {};

          return  putApiContentSetasactive(params,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiContentSetasactiveMutationResult = NonNullable<Awaited<ReturnType<typeof putApiContentSetasactive>>>
    
    export type PutApiContentSetasactiveMutationError = AxiosError<unknown>

    export const usePutApiContentSetasactive = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiContentSetasactive>>, TError,{params?: PutApiContentSetasactiveParams}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiContentSetasactive>>,
        TError,
        {params?: PutApiContentSetasactiveParams},
        TContext
      > => {

      const mutationOptions = getPutApiContentSetasactiveMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const putApiContentPublish = (
    params?: PutApiContentPublishParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.put(
      `/api/content/publish`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getPutApiContentPublishMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiContentPublish>>, TError,{params?: PutApiContentPublishParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof putApiContentPublish>>, TError,{params?: PutApiContentPublishParams}, TContext> => {

const mutationKey = ['putApiContentPublish'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiContentPublish>>, {params?: PutApiContentPublishParams}> = (props) => {
          const {params} = props ?? {};

          return  putApiContentPublish(params,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiContentPublishMutationResult = NonNullable<Awaited<ReturnType<typeof putApiContentPublish>>>
    
    export type PutApiContentPublishMutationError = AxiosError<unknown>

    export const usePutApiContentPublish = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiContentPublish>>, TError,{params?: PutApiContentPublishParams}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiContentPublish>>,
        TError,
        {params?: PutApiContentPublishParams},
        TContext
      > => {

      const mutationOptions = getPutApiContentPublishMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const putApiContentUnpublish = (
    params?: PutApiContentUnpublishParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.put(
      `/api/content/unpublish`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getPutApiContentUnpublishMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiContentUnpublish>>, TError,{params?: PutApiContentUnpublishParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof putApiContentUnpublish>>, TError,{params?: PutApiContentUnpublishParams}, TContext> => {

const mutationKey = ['putApiContentUnpublish'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiContentUnpublish>>, {params?: PutApiContentUnpublishParams}> = (props) => {
          const {params} = props ?? {};

          return  putApiContentUnpublish(params,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiContentUnpublishMutationResult = NonNullable<Awaited<ReturnType<typeof putApiContentUnpublish>>>
    
    export type PutApiContentUnpublishMutationError = AxiosError<unknown>

    export const usePutApiContentUnpublish = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiContentUnpublish>>, TError,{params?: PutApiContentUnpublishParams}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiContentUnpublish>>,
        TError,
        {params?: PutApiContentUnpublishParams},
        TContext
      > => {

      const mutationOptions = getPutApiContentUnpublishMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const deleteApiContentDelete = (
    params?: DeleteApiContentDeleteParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/api/content/delete`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getDeleteApiContentDeleteMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiContentDelete>>, TError,{params?: DeleteApiContentDeleteParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiContentDelete>>, TError,{params?: DeleteApiContentDeleteParams}, TContext> => {

const mutationKey = ['deleteApiContentDelete'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiContentDelete>>, {params?: DeleteApiContentDeleteParams}> = (props) => {
          const {params} = props ?? {};

          return  deleteApiContentDelete(params,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiContentDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiContentDelete>>>
    
    export type DeleteApiContentDeleteMutationError = AxiosError<unknown>

    export const useDeleteApiContentDelete = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiContentDelete>>, TError,{params?: DeleteApiContentDeleteParams}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiContentDelete>>,
        TError,
        {params?: DeleteApiContentDeleteParams},
        TContext
      > => {

      const mutationOptions = getDeleteApiContentDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
