/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * VersionedContentPOC.Server
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export interface Content {
  contentType: string;
  versionId: number;
  contentId: number;
  status: PublishStatus;
  language: Language;
  /** @nullable */
  startPublish?: string | null;
  /** @nullable */
  stopPublish?: string | null;
  contentRoot?: ContentRoot;
  versionCreated?: string;
}

/**
 * @nullable
 */
export type ContentPropertyValueDtoValue = unknown | null;

export interface ContentPropertyValueDto {
  inputType?: InputType;
  isRequired?: boolean;
  /** @nullable */
  value?: ContentPropertyValueDtoValue;
  readOnly?: boolean;
}

export interface ContentReference {
  contentId?: number;
}

/**
 * @nullable
 */
export type ContentRootSharedContentProperties = NewsContentSharedProperties | null;

export interface ContentRoot {
  contentId?: number;
  created?: string;
  /** @nullable */
  sharedContentProperties?: ContentRootSharedContentProperties;
}

export interface ContentRootSummary {
  contentId: number;
  /** @nullable */
  contentTypeName: string | null;
  /** @nullable */
  startPublish: string | null;
  /** @nullable */
  stopPublish: string | null;
  /** @nullable */
  languageVersions: Language[] | null;
  /** @nullable */
  created: string | null;
  /** @nullable */
  lastUpdated: string | null;
}

export type CreateContentRequestPropertiesSchema = {[key: string]: ContentPropertyValueDto};

/**
 * @nullable
 */
export type CreateContentRequestSharedPropertiesSchema = {[key: string]: ContentPropertyValueDto} | null;

export interface CreateContentRequest {
  metadata: CreateContentRequestMetadata;
  propertiesSchema: CreateContentRequestPropertiesSchema;
  /** @nullable */
  sharedPropertiesSchema: CreateContentRequestSharedPropertiesSchema;
}

export interface CreateContentRequestMetadata {
  /** @minLength 1 */
  contentTypeName: string;
  language: Language;
}

export type EventContentContentType = typeof EventContentContentType[keyof typeof EventContentContentType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventContentContentType = {
  EventContent: 'EventContent',
} as const;

export type EventContent = Omit<Content, 'contentType'> & {
  /** @minLength 1 */
  heading: string;
  startDate: string;
  endDate: string;
  /** @minLength 1 */
  description: string;
  contentType: EventContentContentType;
} & Required<Pick<Omit<Content, 'contentType'> & {
  /** @minLength 1 */
  heading: string;
  startDate: string;
  endDate: string;
  /** @minLength 1 */
  description: string;
  contentType: EventContentContentType;
}, 'description' | 'endDate' | 'heading' | 'startDate'>>;

export type InputType = typeof InputType[keyof typeof InputType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InputType = {
  None: 'None',
  Input: 'Input',
  TextArea: 'TextArea',
  DatePicker: 'DatePicker',
  DateTimePicker: 'DateTimePicker',
  Select: 'Select',
  ContentPicker: 'ContentPicker',
} as const;

export type JobContentContentType = typeof JobContentContentType[keyof typeof JobContentContentType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const JobContentContentType = {
  JobContent: 'JobContent',
} as const;

export type JobContent = Omit<Content, 'contentType'> & {
  /** @minLength 1 */
  heading: string;
  /** @minLength 1 */
  lead: string;
  /** @minLength 1 */
  department: string;
  /** @minLength 1 */
  textBody: string;
  /** @minLength 1 */
  workDescription: string;
  /** @minLength 1 */
  requirements: string;
  applicationEndDate: string;
  contentType: JobContentContentType;
} & Required<Pick<Omit<Content, 'contentType'> & {
  /** @minLength 1 */
  heading: string;
  /** @minLength 1 */
  lead: string;
  /** @minLength 1 */
  department: string;
  /** @minLength 1 */
  textBody: string;
  /** @minLength 1 */
  workDescription: string;
  /** @minLength 1 */
  requirements: string;
  applicationEndDate: string;
  contentType: JobContentContentType;
}, 'applicationEndDate' | 'department' | 'heading' | 'lead' | 'requirements' | 'textBody' | 'workDescription'>>;

export type Language = typeof Language[keyof typeof Language];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Language = {
  SV: 'SV',
  EN: 'EN',
} as const;

export type NewsContentContentType = typeof NewsContentContentType[keyof typeof NewsContentContentType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NewsContentContentType = {
  NewsContent: 'NewsContent',
} as const;

export type NewsContent = Omit<Content, 'contentType'> & {
  /** @minLength 1 */
  heading: string;
  /** @nullable */
  lead?: string | null;
  /** @minLength 1 */
  text: string;
  relatedContent?: ContentReference;
  contentType: NewsContentContentType;
} & Required<Pick<Omit<Content, 'contentType'> & {
  /** @minLength 1 */
  heading: string;
  /** @nullable */
  lead?: string | null;
  /** @minLength 1 */
  text: string;
  relatedContent?: ContentReference;
  contentType: NewsContentContentType;
}, 'heading' | 'text'>>;

export type NewsContentSharedPropertiesContentType = typeof NewsContentSharedPropertiesContentType[keyof typeof NewsContentSharedPropertiesContentType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NewsContentSharedPropertiesContentType = {
  NewsContentSharedProperties: 'NewsContentSharedProperties',
} as const;

export type NewsContentSharedProperties = Omit<SharedContentProperties, 'contentType'> & {
  relatedContent?: ContentReference;
  contentType: NewsContentSharedPropertiesContentType;
};

export type PublishStatus = typeof PublishStatus[keyof typeof PublishStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PublishStatus = {
  Draft: 'Draft',
  Published: 'Published',
  DelayedPublish: 'DelayedPublish',
  Unpublished: 'Unpublished',
} as const;

export interface SharedContentProperties {
  contentType: string;
}

export type UpdateContentRequestPropertiesSchema = {[key: string]: ContentPropertyValueDto};

/**
 * @nullable
 */
export type UpdateContentRequestSharedPropertiesSchema = {[key: string]: ContentPropertyValueDto} | null;

export interface UpdateContentRequest {
  metadata: UpdateContentRequestMetadata;
  propertiesSchema: UpdateContentRequestPropertiesSchema;
  /** @nullable */
  sharedPropertiesSchema: UpdateContentRequestSharedPropertiesSchema;
}

export interface UpdateContentRequestMetadata {
  contentId: number;
  versionId: number;
  language: Language;
  /** @nullable */
  created: string | null;
  status: PublishStatus;
  /** @nullable */
  startPublish: string | null;
  /** @nullable */
  stopPublish: string | null;
  /** @nullable */
  languageTranslations: Language[] | null;
  forceNewVersion?: boolean;
  /** @minLength 1 */
  contentTypeName: string;
}

export interface ValidationResult {
  /** @nullable */
  readonly memberNames?: readonly string[] | null;
  /** @nullable */
  errorMessage?: string | null;
}

export type GetApiContentGetParams = {
contentId?: number;
language?: Language;
};

export type GetApiContentGet200 = EventContent | JobContent | NewsContent;

export type GetApiContentAllParams = {
language?: Language;
};

export type GetApiContentAll200Item = EventContent | JobContent | NewsContent;

export type GetApiContentCreationschemaParams = {
contentTypeName?: string;
language?: Language;
};

export type PostApiContentCreate200 = EventContent | JobContent | NewsContent;

export type GetApiContentUpdateschemaParams = {
contentId?: number;
language?: Language;
versionId?: number;
};

export type PutApiContentUpdate200 = EventContent | JobContent | NewsContent;

export type GetApiContentVersionsParams = {
contentId?: number;
language?: Language;
};

export type GetApiContentVersions200Item = EventContent | JobContent | NewsContent;

export type PutApiContentPublishParams = {
versionId?: number;
};

export type PutApiContentUnpublishParams = {
versionId?: number;
};

export type DeleteApiContentDeleteParams = {
contentId?: number;
};

export type GetApiContentsummaryContentrootsParams = {
ContentType?: string;
Published?: boolean;
Language?: Language;
};

export type PostApiValidationPropertyParams = {
contentTypeName?: string;
propertyName?: string;
};

export const getApiContentGet = (
    params?: GetApiContentGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetApiContentGet200>> => {
    
    
    return axios.default.get(
      `/api/content/get`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getGetApiContentGetQueryKey = (params?: GetApiContentGetParams,) => {
    return [
    `/api/content/get`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiContentGetQueryOptions = <TData = Awaited<ReturnType<typeof getApiContentGet>>, TError = AxiosError<unknown>>(params?: GetApiContentGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiContentGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiContentGet>>> = ({ signal }) => getApiContentGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiContentGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiContentGetQueryResult = NonNullable<Awaited<ReturnType<typeof getApiContentGet>>>
export type GetApiContentGetQueryError = AxiosError<unknown>


export function useGetApiContentGet<TData = Awaited<ReturnType<typeof getApiContentGet>>, TError = AxiosError<unknown>>(
 params: undefined |  GetApiContentGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiContentGet>>,
          TError,
          Awaited<ReturnType<typeof getApiContentGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiContentGet<TData = Awaited<ReturnType<typeof getApiContentGet>>, TError = AxiosError<unknown>>(
 params?: GetApiContentGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiContentGet>>,
          TError,
          Awaited<ReturnType<typeof getApiContentGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiContentGet<TData = Awaited<ReturnType<typeof getApiContentGet>>, TError = AxiosError<unknown>>(
 params?: GetApiContentGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiContentGet<TData = Awaited<ReturnType<typeof getApiContentGet>>, TError = AxiosError<unknown>>(
 params?: GetApiContentGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiContentGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const getApiContentAll = (
    params?: GetApiContentAllParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetApiContentAll200Item[]>> => {
    
    
    return axios.default.get(
      `/api/content/all`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getGetApiContentAllQueryKey = (params?: GetApiContentAllParams,) => {
    return [
    `/api/content/all`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiContentAllQueryOptions = <TData = Awaited<ReturnType<typeof getApiContentAll>>, TError = AxiosError<unknown>>(params?: GetApiContentAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentAll>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiContentAllQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiContentAll>>> = ({ signal }) => getApiContentAll(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiContentAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiContentAllQueryResult = NonNullable<Awaited<ReturnType<typeof getApiContentAll>>>
export type GetApiContentAllQueryError = AxiosError<unknown>


export function useGetApiContentAll<TData = Awaited<ReturnType<typeof getApiContentAll>>, TError = AxiosError<unknown>>(
 params: undefined |  GetApiContentAllParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiContentAll>>,
          TError,
          Awaited<ReturnType<typeof getApiContentAll>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiContentAll<TData = Awaited<ReturnType<typeof getApiContentAll>>, TError = AxiosError<unknown>>(
 params?: GetApiContentAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiContentAll>>,
          TError,
          Awaited<ReturnType<typeof getApiContentAll>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiContentAll<TData = Awaited<ReturnType<typeof getApiContentAll>>, TError = AxiosError<unknown>>(
 params?: GetApiContentAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentAll>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiContentAll<TData = Awaited<ReturnType<typeof getApiContentAll>>, TError = AxiosError<unknown>>(
 params?: GetApiContentAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentAll>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiContentAllQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const getApiContentTypes = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<string[]>> => {
    
    
    return axios.default.get(
      `/api/content/types`,options
    );
  }




export const getGetApiContentTypesQueryKey = () => {
    return [
    `/api/content/types`
    ] as const;
    }

    
export const getGetApiContentTypesQueryOptions = <TData = Awaited<ReturnType<typeof getApiContentTypes>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentTypes>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiContentTypesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiContentTypes>>> = ({ signal }) => getApiContentTypes({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiContentTypes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiContentTypesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiContentTypes>>>
export type GetApiContentTypesQueryError = AxiosError<unknown>


export function useGetApiContentTypes<TData = Awaited<ReturnType<typeof getApiContentTypes>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentTypes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiContentTypes>>,
          TError,
          Awaited<ReturnType<typeof getApiContentTypes>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiContentTypes<TData = Awaited<ReturnType<typeof getApiContentTypes>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentTypes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiContentTypes>>,
          TError,
          Awaited<ReturnType<typeof getApiContentTypes>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiContentTypes<TData = Awaited<ReturnType<typeof getApiContentTypes>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentTypes>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiContentTypes<TData = Awaited<ReturnType<typeof getApiContentTypes>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentTypes>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiContentTypesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const getApiContentCreationschema = (
    params?: GetApiContentCreationschemaParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CreateContentRequest>> => {
    
    
    return axios.default.get(
      `/api/content/creationschema`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getGetApiContentCreationschemaQueryKey = (params?: GetApiContentCreationschemaParams,) => {
    return [
    `/api/content/creationschema`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiContentCreationschemaQueryOptions = <TData = Awaited<ReturnType<typeof getApiContentCreationschema>>, TError = AxiosError<unknown>>(params?: GetApiContentCreationschemaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentCreationschema>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiContentCreationschemaQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiContentCreationschema>>> = ({ signal }) => getApiContentCreationschema(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiContentCreationschema>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiContentCreationschemaQueryResult = NonNullable<Awaited<ReturnType<typeof getApiContentCreationschema>>>
export type GetApiContentCreationschemaQueryError = AxiosError<unknown>


export function useGetApiContentCreationschema<TData = Awaited<ReturnType<typeof getApiContentCreationschema>>, TError = AxiosError<unknown>>(
 params: undefined |  GetApiContentCreationschemaParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentCreationschema>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiContentCreationschema>>,
          TError,
          Awaited<ReturnType<typeof getApiContentCreationschema>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiContentCreationschema<TData = Awaited<ReturnType<typeof getApiContentCreationschema>>, TError = AxiosError<unknown>>(
 params?: GetApiContentCreationschemaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentCreationschema>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiContentCreationschema>>,
          TError,
          Awaited<ReturnType<typeof getApiContentCreationschema>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiContentCreationschema<TData = Awaited<ReturnType<typeof getApiContentCreationschema>>, TError = AxiosError<unknown>>(
 params?: GetApiContentCreationschemaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentCreationschema>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiContentCreationschema<TData = Awaited<ReturnType<typeof getApiContentCreationschema>>, TError = AxiosError<unknown>>(
 params?: GetApiContentCreationschemaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentCreationschema>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiContentCreationschemaQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const postApiContentCreate = (
    createContentRequest: CreateContentRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PostApiContentCreate200>> => {
    
    
    return axios.default.post(
      `/api/content/create`,
      createContentRequest,options
    );
  }



export const getPostApiContentCreateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiContentCreate>>, TError,{data: CreateContentRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiContentCreate>>, TError,{data: CreateContentRequest}, TContext> => {

const mutationKey = ['postApiContentCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiContentCreate>>, {data: CreateContentRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiContentCreate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiContentCreateMutationResult = NonNullable<Awaited<ReturnType<typeof postApiContentCreate>>>
    export type PostApiContentCreateMutationBody = CreateContentRequest
    export type PostApiContentCreateMutationError = AxiosError<unknown>

    export const usePostApiContentCreate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiContentCreate>>, TError,{data: CreateContentRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiContentCreate>>,
        TError,
        {data: CreateContentRequest},
        TContext
      > => {

      const mutationOptions = getPostApiContentCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const getApiContentUpdateschema = (
    params?: GetApiContentUpdateschemaParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UpdateContentRequest>> => {
    
    
    return axios.default.get(
      `/api/content/updateschema`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getGetApiContentUpdateschemaQueryKey = (params?: GetApiContentUpdateschemaParams,) => {
    return [
    `/api/content/updateschema`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiContentUpdateschemaQueryOptions = <TData = Awaited<ReturnType<typeof getApiContentUpdateschema>>, TError = AxiosError<unknown>>(params?: GetApiContentUpdateschemaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentUpdateschema>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiContentUpdateschemaQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiContentUpdateschema>>> = ({ signal }) => getApiContentUpdateschema(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiContentUpdateschema>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiContentUpdateschemaQueryResult = NonNullable<Awaited<ReturnType<typeof getApiContentUpdateschema>>>
export type GetApiContentUpdateschemaQueryError = AxiosError<unknown>


export function useGetApiContentUpdateschema<TData = Awaited<ReturnType<typeof getApiContentUpdateschema>>, TError = AxiosError<unknown>>(
 params: undefined |  GetApiContentUpdateschemaParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentUpdateschema>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiContentUpdateschema>>,
          TError,
          Awaited<ReturnType<typeof getApiContentUpdateschema>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiContentUpdateschema<TData = Awaited<ReturnType<typeof getApiContentUpdateschema>>, TError = AxiosError<unknown>>(
 params?: GetApiContentUpdateschemaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentUpdateschema>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiContentUpdateschema>>,
          TError,
          Awaited<ReturnType<typeof getApiContentUpdateschema>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiContentUpdateschema<TData = Awaited<ReturnType<typeof getApiContentUpdateschema>>, TError = AxiosError<unknown>>(
 params?: GetApiContentUpdateschemaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentUpdateschema>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiContentUpdateschema<TData = Awaited<ReturnType<typeof getApiContentUpdateschema>>, TError = AxiosError<unknown>>(
 params?: GetApiContentUpdateschemaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentUpdateschema>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiContentUpdateschemaQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const putApiContentUpdate = (
    updateContentRequest: UpdateContentRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PutApiContentUpdate200>> => {
    
    
    return axios.default.put(
      `/api/content/update`,
      updateContentRequest,options
    );
  }



export const getPutApiContentUpdateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiContentUpdate>>, TError,{data: UpdateContentRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof putApiContentUpdate>>, TError,{data: UpdateContentRequest}, TContext> => {

const mutationKey = ['putApiContentUpdate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiContentUpdate>>, {data: UpdateContentRequest}> = (props) => {
          const {data} = props ?? {};

          return  putApiContentUpdate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiContentUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof putApiContentUpdate>>>
    export type PutApiContentUpdateMutationBody = UpdateContentRequest
    export type PutApiContentUpdateMutationError = AxiosError<unknown>

    export const usePutApiContentUpdate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiContentUpdate>>, TError,{data: UpdateContentRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiContentUpdate>>,
        TError,
        {data: UpdateContentRequest},
        TContext
      > => {

      const mutationOptions = getPutApiContentUpdateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const getApiContentVersions = (
    params?: GetApiContentVersionsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetApiContentVersions200Item[]>> => {
    
    
    return axios.default.get(
      `/api/content/versions`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getGetApiContentVersionsQueryKey = (params?: GetApiContentVersionsParams,) => {
    return [
    `/api/content/versions`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiContentVersionsQueryOptions = <TData = Awaited<ReturnType<typeof getApiContentVersions>>, TError = AxiosError<unknown>>(params?: GetApiContentVersionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentVersions>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiContentVersionsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiContentVersions>>> = ({ signal }) => getApiContentVersions(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiContentVersions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiContentVersionsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiContentVersions>>>
export type GetApiContentVersionsQueryError = AxiosError<unknown>


export function useGetApiContentVersions<TData = Awaited<ReturnType<typeof getApiContentVersions>>, TError = AxiosError<unknown>>(
 params: undefined |  GetApiContentVersionsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentVersions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiContentVersions>>,
          TError,
          Awaited<ReturnType<typeof getApiContentVersions>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiContentVersions<TData = Awaited<ReturnType<typeof getApiContentVersions>>, TError = AxiosError<unknown>>(
 params?: GetApiContentVersionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentVersions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiContentVersions>>,
          TError,
          Awaited<ReturnType<typeof getApiContentVersions>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiContentVersions<TData = Awaited<ReturnType<typeof getApiContentVersions>>, TError = AxiosError<unknown>>(
 params?: GetApiContentVersionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentVersions>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiContentVersions<TData = Awaited<ReturnType<typeof getApiContentVersions>>, TError = AxiosError<unknown>>(
 params?: GetApiContentVersionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentVersions>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiContentVersionsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const putApiContentPublish = (
    params?: PutApiContentPublishParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.put(
      `/api/content/publish`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getPutApiContentPublishMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiContentPublish>>, TError,{params?: PutApiContentPublishParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof putApiContentPublish>>, TError,{params?: PutApiContentPublishParams}, TContext> => {

const mutationKey = ['putApiContentPublish'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiContentPublish>>, {params?: PutApiContentPublishParams}> = (props) => {
          const {params} = props ?? {};

          return  putApiContentPublish(params,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiContentPublishMutationResult = NonNullable<Awaited<ReturnType<typeof putApiContentPublish>>>
    
    export type PutApiContentPublishMutationError = AxiosError<unknown>

    export const usePutApiContentPublish = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiContentPublish>>, TError,{params?: PutApiContentPublishParams}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiContentPublish>>,
        TError,
        {params?: PutApiContentPublishParams},
        TContext
      > => {

      const mutationOptions = getPutApiContentPublishMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const putApiContentUnpublish = (
    params?: PutApiContentUnpublishParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.put(
      `/api/content/unpublish`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getPutApiContentUnpublishMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiContentUnpublish>>, TError,{params?: PutApiContentUnpublishParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof putApiContentUnpublish>>, TError,{params?: PutApiContentUnpublishParams}, TContext> => {

const mutationKey = ['putApiContentUnpublish'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiContentUnpublish>>, {params?: PutApiContentUnpublishParams}> = (props) => {
          const {params} = props ?? {};

          return  putApiContentUnpublish(params,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiContentUnpublishMutationResult = NonNullable<Awaited<ReturnType<typeof putApiContentUnpublish>>>
    
    export type PutApiContentUnpublishMutationError = AxiosError<unknown>

    export const usePutApiContentUnpublish = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiContentUnpublish>>, TError,{params?: PutApiContentUnpublishParams}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiContentUnpublish>>,
        TError,
        {params?: PutApiContentUnpublishParams},
        TContext
      > => {

      const mutationOptions = getPutApiContentUnpublishMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const deleteApiContentDelete = (
    params?: DeleteApiContentDeleteParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/api/content/delete`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getDeleteApiContentDeleteMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiContentDelete>>, TError,{params?: DeleteApiContentDeleteParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiContentDelete>>, TError,{params?: DeleteApiContentDeleteParams}, TContext> => {

const mutationKey = ['deleteApiContentDelete'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiContentDelete>>, {params?: DeleteApiContentDeleteParams}> = (props) => {
          const {params} = props ?? {};

          return  deleteApiContentDelete(params,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiContentDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiContentDelete>>>
    
    export type DeleteApiContentDeleteMutationError = AxiosError<unknown>

    export const useDeleteApiContentDelete = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiContentDelete>>, TError,{params?: DeleteApiContentDeleteParams}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiContentDelete>>,
        TError,
        {params?: DeleteApiContentDeleteParams},
        TContext
      > => {

      const mutationOptions = getDeleteApiContentDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const getApiContentsummaryContentroots = (
    params?: GetApiContentsummaryContentrootsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ContentRootSummary[]>> => {
    
    
    return axios.default.get(
      `/api/contentsummary/contentroots`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getGetApiContentsummaryContentrootsQueryKey = (params?: GetApiContentsummaryContentrootsParams,) => {
    return [
    `/api/contentsummary/contentroots`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiContentsummaryContentrootsQueryOptions = <TData = Awaited<ReturnType<typeof getApiContentsummaryContentroots>>, TError = AxiosError<unknown>>(params?: GetApiContentsummaryContentrootsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentsummaryContentroots>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiContentsummaryContentrootsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiContentsummaryContentroots>>> = ({ signal }) => getApiContentsummaryContentroots(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiContentsummaryContentroots>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiContentsummaryContentrootsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiContentsummaryContentroots>>>
export type GetApiContentsummaryContentrootsQueryError = AxiosError<unknown>


export function useGetApiContentsummaryContentroots<TData = Awaited<ReturnType<typeof getApiContentsummaryContentroots>>, TError = AxiosError<unknown>>(
 params: undefined |  GetApiContentsummaryContentrootsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentsummaryContentroots>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiContentsummaryContentroots>>,
          TError,
          Awaited<ReturnType<typeof getApiContentsummaryContentroots>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiContentsummaryContentroots<TData = Awaited<ReturnType<typeof getApiContentsummaryContentroots>>, TError = AxiosError<unknown>>(
 params?: GetApiContentsummaryContentrootsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentsummaryContentroots>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiContentsummaryContentroots>>,
          TError,
          Awaited<ReturnType<typeof getApiContentsummaryContentroots>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiContentsummaryContentroots<TData = Awaited<ReturnType<typeof getApiContentsummaryContentroots>>, TError = AxiosError<unknown>>(
 params?: GetApiContentsummaryContentrootsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentsummaryContentroots>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiContentsummaryContentroots<TData = Awaited<ReturnType<typeof getApiContentsummaryContentroots>>, TError = AxiosError<unknown>>(
 params?: GetApiContentsummaryContentrootsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContentsummaryContentroots>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiContentsummaryContentrootsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const postApiValidationProperty = (
    contentPropertyValueDto: ContentPropertyValueDto,
    params?: PostApiValidationPropertyParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ValidationResult[]>> => {
    
    
    return axios.default.post(
      `/api/validation/property`,
      contentPropertyValueDto,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getPostApiValidationPropertyMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiValidationProperty>>, TError,{data: ContentPropertyValueDto;params?: PostApiValidationPropertyParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiValidationProperty>>, TError,{data: ContentPropertyValueDto;params?: PostApiValidationPropertyParams}, TContext> => {

const mutationKey = ['postApiValidationProperty'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiValidationProperty>>, {data: ContentPropertyValueDto;params?: PostApiValidationPropertyParams}> = (props) => {
          const {data,params} = props ?? {};

          return  postApiValidationProperty(data,params,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiValidationPropertyMutationResult = NonNullable<Awaited<ReturnType<typeof postApiValidationProperty>>>
    export type PostApiValidationPropertyMutationBody = ContentPropertyValueDto
    export type PostApiValidationPropertyMutationError = AxiosError<unknown>

    export const usePostApiValidationProperty = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiValidationProperty>>, TError,{data: ContentPropertyValueDto;params?: PostApiValidationPropertyParams}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiValidationProperty>>,
        TError,
        {data: ContentPropertyValueDto;params?: PostApiValidationPropertyParams},
        TContext
      > => {

      const mutationOptions = getPostApiValidationPropertyMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
